name: Update Recent Activity

on:
  schedule:
    # Runs every 30 minutes
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with Recent Activity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update GitHub Activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "⚡ Auto-update: recent activity"
          MAX_LINES: 6
